language: java
cache:
  directories:
  - "$HOME/.m2"
jdk:
- oraclejdk8
sudo: required
services:
- docker
script:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- mvn clean package dockerfile:build dockerfile:push
before_install:
- chmod +x mvnw
notifications:
  email:
    on_success: never
    on_failure: never
env:
  matrix:
  - secure: UR/eaXf5hrY91yRYvDP8HzZirebucrn3GvQISbXEAbcInfSXvW0l0spC8x5k7e+koVG81nISSucLqMNbCOj+2Fr8fbPIVU28HV/AyxyryFJvRKoMabUX++sKOno56xZvdlYIZb95qcljnKfWlvoLRHzC3TjNZLQp4WH5jodmMTiuJUWg4KX8BDfnHjTh3vN51ocnUg+3JfeWQ2ENvAOyty4w9Z+Bv5p8Jrke0MpMYe4Nt3fwl/SD/uDc6GZNuqUQUtqG3GOaKKm1L9G3nl250c1OD5nUe48cRuyrHO1A0dbSxyV2gYRZABRa40lvvB/fDYdi657ib81NQR3H3k1drH+XzM7P8qKQScMYep1Lbu3L7EuLnFyUZijTTDVTsE8ktF/SQ+H6FEDROJSSvAIN/Rxlh+vdTa7I7mUgBWL100eLhm/bIo++pvh1SDv5Ut6f2+dQrwtI2j56yKIx69KMg5EnMSXo0yunp1NnA90vbfZYrmYM607s8ZXao9ekWZqI5pXWgviFOZnMSPHDJaeQ/qy2gaqeZA6obMtt6HPO3yYm2AoXE4ejMvmPpRyRpAVcJeZII4dd/Ylr2Tgd5rJabLUnDGOg/r/AFbfxXrIJ4yGS6u11VvPnOORiSFEcdl0GzYvJnyiEDeV0R+DQHErXrIiIKsu7BTIhUQXrXHybM7o=
  - secure: qHVJJWhkMkOsfaVKxazY2IefpwM7Kr7kIRvTdJ8qVKA3BnEbF1a5P8gjPYlPdHIYwAmZYaiRNJBMJaws15pXPOVVfd3lB0OywZEeMfhvxiG9lum/LxZWBZjdv1JrDjBIkJsHrOqLgVvi+x98/ZUPOO4TH4GfBu4MQbCvwfMgatLang7LhGp3lztZ7LQw6XJ4otLOV9DI0ZlwnECYjTXfwO9i2ukEDtytCyfTxivR0RLwQZK2wxuox1XqkNuEv0wKsxekIEx9VM7UzsOXUZ7OfVs7yfoWzBc1lz0gaXau2SELMnYK1PdU3VbvUGu6mFcFcFauoT6Nde4XCMyMRZ9bI+q/nbIGnY3DWZ0CAPuwPrFrxnO+59zehui9M0hL6H6RVDk+2FDUE9kNa62n75JaS2nmaz2wZFg7dfAkgIooQKCzs5ypsdp4y70ze8AiGycDeqpVA9mlHINeM4wfs0zTB/HuXdYoTE/5F/cb+0trkr4OzQV0Yy9fY++WZ/8zDJDyQJnzYK7JEur2SKDFf+JLcPgBiwzoOemD456c0xEIwTxSLebTmPYJsQ0J+U8EsjegpMrfGr4Bd7U2tG0fSwFFtKlcfAlElsrIS0TWC1Fei9N8Uf5q51tZMkexP7enJRjlm21JhRTrNR1WkVa1UABtrBKr8TsJfzidjPCXZmd+Wfo=
