language: java
cache:
  directories:
  - "$HOME/.m2"
jdk:
- oraclejdk8
sudo: required
services:
- docker
script:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- mvn clean package dockerfile:build dockerfile:push
before_install:
- chmod +x mvnw
notifications:
  email:
    on_success: never
    on_failure: never
env:
  matrix:
  - secure: WlPFc4duK7SOZuYy7zmG8B1umW1tCDFfjLVprvhztaf2ykYTTptiTVCCORFx+PSUOVM67HcISpWep9nFStgTC8nYn0VHb4cfwujOwylBkamQkNezhu4a7tcuIEEdhA7gewj/KxX/tYhdj8V99bItPcrK9bbMqwt9ZWt0z4B0j9L92x/+m0RMf7x6LBa3wdcjBifOccMvZb4pnr26U10Dhnc4enbaWVwDXJuwwoqhH5x9lFsm8zTTphLOjTZldgJcqbP+ZOg/aA6JTNFDwbbO7UWJpnzTGJn0LhwKfjVnuce3xmC+SQgjCKhbBLpgORHvdHBpzvXynrIP6SyG+fozuvTQtS1hpz+PujGm5uZr18GkZDgZ0AI/LTbl0rM1n1CY3kuJSWWmmsfenTwrxIxFjbd5/76jyRpZqLzF/vVZCytsKoQ+t18iZQrjuq3DWvW/tQjy/j5NB0e6dxI8H99uvguOgqUf827ejTb0/YQQtxKAtwRe5419+OU/1mKJP0rnuYsZD9GzG8r7S6+KXB0sd3kbqfvjugKmLy00JGmTTQD21UWJ4sYshtuBI2KQuflrGpYTDTg1U6DQChqC7X4dmB5fDWi5I+2QFgCgo6y7mnm7M2Vw1XpK/OFi1FxE7uVmdGkLUGBWra/Q+kS2u0Kotv0EAuu3i8sjYCjSClM+8/A=
  - secure: eF1f6gCp6OvhVmN6x1eCZ1DRqo8FmA3+zpR5qoz0QIPM2KiI4uf6fkQL60N3rIUHSMRrRE82vG1m/OLNL9CzIS58vIB8c0Zz5821zU+eOVh/b1lBWDatYzPscK/Suhx2FZMD3IeuAeX/IS0bt+WBgAxzIliN95pSw9XBUjOkdmqCyisoHXUxbROQoHO1v4FU+wIUOf9YHXwhEAiDzsT+f1WhwN20VR4l4LwD9WtVHF4wQx04P0+StoT20lc/gvYuUpkxEpNJKdsAMIMg9rDKDcyH2KqAKt7te71cpCQAK2iKnsZZd0dbb6XCfDTwwBmOPDD+hyGqsqWt3fVCQx8GeP65lLFiutFp5ZDPQOa5HVjZxZp3yQfuUnxhOCSVauNkpw2/CjBm9P5NULZDtaV6rOjYNTEXxR4B3YsakIrm2zakCAYiSVfSyKS+hLvqnuZC4E8cHt6jR6eM0eUu2gnZcMPW4okAXXeWQNLqlfTZwSoMKek+j63yUnRGRkSq9ta8CSwVskZayZwQWUFIjhb2WaQdmR8eUNjYCNmevTzYik9oUdqv32fB7NG8ItsvOShaS/FPm1qAP1VYrA6Lfb5kvhu1tw2SllVRQ9oM96O5sNPK2ErU31LYUiWThhk4oEJRdH3H8PuzVEusxjZux5bDvnZ5kv4O8xf3oD5mWOfbf0I=
