language: java
cache:
  directories:
  - "$HOME/.m2"
jdk:
- oraclejdk8
sudo: required
services:
- docker
script:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- mvn clean package dockerfile:build dockerfile:push
before_install:
- chmod +x mvnw
env:
  matrix:
  - secure: ImQQQVlw8viB6Cgzi5gKV9R8KQXeUcd+M8IU3Vlm8TDrRdhywFEGsHUc43FYcgzf9VbddOMFDOustuFpzQ7l6ktdLwfWfHJiJVgSyQyBguN4/ysRkXM8BPRacc5ks9GP4v8gc6phT0cJ6EWcoeSOQwNQCaxhScPcNzz+T2GS6r7wQsK8QgSGwzlg7g7bFlaKHeyfhrsIMI86oeZnFZue9L8MmVCzEsiZZetvvIv3oE7IdszWZg0RLtft4mK/DFr1RLLs96bz7PUfeY3wjPkKAn6Z1eWoA6e3TBr+eo9iEz4rRMegUjRvtWcajuPWWyCB78HLkzI6ylWjiw7/8DBN0RztLkeM7HUAVhw4pPS4HMkRHk/ryCqO1qHB4wwGd5Ma3fYPUtlviXwP5wGBAMjfSDr8+v51cUGjomIEHaAtdR9Zg7wiNbg7Qfod8e8Xqy0xaA+HiPG5PSOy+V+D76P7nWhvg9jMFte8yxqz3X9G+Elf9tnUDjUEK3GFESfRmuF1AYuE8+GmoFD4N7lffDd1RnkgTdpzl9Ep4ANj01buvrF1sfuNpgZX23K9zzrZPkrnVjGsndN43Lcg9Q+7IpxDJwxy/d18qKRu9DsPPXVNVCsnKwQ7o3TPgqYMSdRtA+9zj4RtQkqFltBNjSrEmrzxjNFJDwE/XWqESZGmz46fjbQ=
  - secure: RA/VuIaWnBPKNmSS6rHmWwry+vKVTnbWprgnACFklEsTXl6EW9jzlmO/x6JTfwbkbSqMTb/vh4NbT/0heKnXUjWEDeQWmDYD6heQmDEifEzd04H4r2rbRaWaUKCsKlkPQp38ZtSdZtwTruT2mJSbEM1DGqF/ElWv6+k42eXo07yd2sbcs4pAFb5IftY1cb/e6sTK3YhuG5z6TJM2X5nITqSJI5k21RNjX0Fqq3YybPOEU1J15cCbH6xyvKKQRuuJ4fCZ6YQVpY19yoZHHdSDSAmzUh/lpMavFnF5D/JjSjQi1J9J0xnrP/Qgk887fPCotA7viBwsUVC2EACYJNoyA8dgNRcWMrHsZFJ1nPWnWXKC3gjEWclZoDY3bKelz9al8AyiR9sjgtYZxoKtF4EOXLjEN3rKutkh0cLKUb2k9k7hwVTWvl1tQGOHbvUNeLlAbJzQLkh/stbaS8e4cw+X5PL/H/0VN1o8IVMSwzBErRa8oXJ5OPV921cnvJmgyAkXaVM1USxzGYIjIsFXUhW9wuDw63/yRb1S8bFEBHF3P5x/OVtBaZvrC99N3+tv0RphyK1mvEx7qduvtMu+/gNzGeJAmPgIUizZtblWq3b43oUAiK9TBDYopwisgUWxONxM4JDyhK2dtorSAM6Lc3WWdb3mglUs8XBinBgUnuzVJQw=
