language: java
cache:
  directories:
  - "$HOME/.m2"
jdk:
- oraclejdk8
sudo: required
services:
- docker
script:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- mvn clean package dockerfile:build dockerfile:push
before_install:
- chmod +x mvnw
notifications:
  email:
    on_success: never
    on_failure: never
env:
  matrix:
  - secure: U56M9tGvitqgxz0/uRX02PxWEf64xb69JkAf+JthYfkORyMZb/0J8XZcHg98bBnEXSXYcTEk00Dwperq8IXrNHLoF2RT1GMDFstTqyeGXjs3uOgxAcKRwaLM13ipjnk7/8C7uI/a9KJy8OQJVIdUwGh3ccMDAr7MG+I03g37wj1QZVAr8hDGh5j42Ehg5HuA1hM/Lti9fDkaTgA4EFCnoy7quZa401+UjLi3F6fjMURJDeytRhPZ2ig03jtlczwAeYmxRux1ZsH7gjRf9HfLsQaQd9USBpD4IQ4elIn1tIOh/seTMs08zpJY9QB5deUBj0vMYqu4fujQxwsR7QEHSfI4GFgvRjYlEV+HEFbjXKWt+gA3i8UWaZiAYruUYHkKb9eaLyarEVjLP1v8rBlgysrmLBE3oqK+6ZtxMFd6OboIZd3gcrWvINFbeamPXK2pOvGbXm95vJ+bYRaX0dwuKG3fmh8Do5IYXUVWMJeIft0bPv8/zN9PdcTmGzvTGIztfVzX5JhKW0UZdd3hFKfx2UbyabKrfeNfa1g7CuSRi1F5cyt42wjnjd+Ri6u6IWjDq/i879NNQL7qcDU0MkVlE9CTLIEXYS4zz1swm3yjjXqWUsEXGI9oNGel9gMmqwrbYW0r/uUwq+5iKaPSW8tcaQseNX4OcU+Kfo+5W7cKOkQ=
  - secure: VP90DUkJR1INTDr7QbU3Cgl1QAf+repMsLFHAS3Siyy/aggYo4kuVKeK69T147+ZmHw3S+tiRmRhKy5ewbPSrA0CYMF/fSf70JSTX/BDdX7kA8U5VBuf5+f1P+UAP0zWIRJSgDSI2QOgTwSSpssm5SqH0S4V5GvlNqorR67y0bSxeS5sT94/hxW5TfQZYplsnBiXgl0OOgtoBEZqsywQ7d6b9Co9nCrHe2cQRIx6PgE0V2JN2gli7Th7+JJlCskl9Nlznrv3gAvwtjPABZtJrHISMmrockrz+jRSDamKWUK3l7QXynMvOc43Gw+9y5i/XNUoWrOupgMAxSmt1MngwtzrZwWziGYTVIom9QemU2+/DkKVHpmkXAhBH5/KCp2xOQnP7YrxQjC0L0TqwuBGk6/j1CVNCX0d4YzhlMloVRTIBbxW/mdkhERD0PAvWAHQQOdOA+PFHEzNsMNfaKzx0RtDaZT02481suTJTgB95rne0NrSEikkkOFQFVxc+uFyoSL4iDfQJCYHFnrF5TnBQYe6GPHIBjltAThQUqfTIaMyffiheW8J/FYAB4zaHS03eskwiMgW3BQ+Y03TQkvLYyic6+61Q4OOgNVsme3azGpmrxPZQ5Kw1kx84ajUNCvPk5wT39cAE1m3wYJMs0KJ9GcU+9Zl9FJQFSkKlIcd9vY=
