        
server:
 port: 0    
 
eureka:
 instance:
  leaseRenewalIntervalInSeconds: 10
  instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
 client: 
  registryFetchIntervalSeconds: 5 
    
---

spring:
  profiles: docker
  
eureka:
 instance:
  hostname: service-instance-service
 client:
  serviceUrl:
   defaultZone: http://eureka-service:8761/eureka/    

